# Generated by Django 5.1.1 on 2024-10-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='uses',
        ),
    ]
