# Generated by Django 5.1.2 on 2024-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_prodapp_product_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AR', 'Pencil'), ('OG', 'Pencil Box'), ('DB', 'Pen'), ('PS', 'Ruler'), ('SS', 'Ruled Note'), ('DF', 'Unruled Note'), ('CN', 'Eraser'), ('BE', 'Sharpener')], max_length=2),
        ),
    ]
