# Generated by Django 5.1.1 on 2024-11-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
